version: '3'
services:
  app:
    build: .
    platform: linux/arm64 # Menentukan platform untuk image
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - PORT=3000
      - POSTGREHOST=db
      - POSTGRESUSER=postgres
      - POSTGRESPASSWORD=postgres
      - POSTGRESPORT=5432
      - POSTGREDB=learn-express-rest-api
  db:
    image: arm64v8/postgres:13 # Menggunakan image PostgreSQL untuk ARM64
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=learn-express-rest-api
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
