version: '3'
name: learn-nodejs-api
services:
  app:
    build: .
    platform: linux/amd64
    ports:
      - '3000'
    depends_on:
      - db
    environment:
      - PORT=3000
      - POSTGREHOST=db
      - POSTGRESUSER=postgres
      - POSTGRESPASSWORD=postgres
      - POSTGRESPORT=5432
      - POSTGREDB=learn-express-rest-api
      - COMPOSE_PROJECT_NAME=learn-nodejs-api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=learn-express-rest-api
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - backups:/usr/src/app/backups

  backup:
    image: postgres:13
    depends_on:
      - db
    volumes:
      - ./backup:/backup
    command: >
      bash -c "while true; do
        PGPASSWORD=$${POSTGRES_PASSWORD} pg_dump -h db -U $${POSTGRES_USER} -Fc $${POSTGRES_DB} > /backup/$$(date +%Y-%m-%d-%H-%M-%S).dump
        echo \"Backup done at $$(date +%Y-%m-%d_%H:%M:%S)\"
        ls -1 /backup/*.dump | head -n -2 | xargs rm -f
        sleep 60
      done"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: learn-express-rest-api

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
volumes:
  postgres_data:
  backups:
