version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - PORT=3000
      - POSTGREHOST=db
      - POSTGRESUSER=postgres
      - POSTGRESPASSWORD=postgres
      - POSTGRESPORT=5432
      - POSTGREDB=learn-express-rest-api
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=learn-express-rest-api
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
